import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>My Portfolio Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <a1>Web App</a1>
          <a2>created with NEXTjs</a2>
        </div>

        <div className={styles.navBar}>
          <navTab>
          Home
          </navTab>

          <navTab>
          About Me
          </navTab>

          <navTab>
          WebServices
          </navTab>
        </div>

        <div className={styles.body}>
          <p>Douglass, Real Time UML, 3E: Advances in The UML for Real-Time Systems
          Eeles et al., Building J2EETM Applications with the Rational Unified Process Fowler, Analysis Patterns: Reusable Object Models
          Fowler, UML Distilled, 3E: A Brief Guide to the Standard Object Modeling Language
          Fowler et al., Refactoring: Improving the Design of Existing Code
          Gomaa, Designing Concurrent, Distributed, and Real-Time Applications
          with UML Gomaa, Designing Software Product Lines with UML
          Heinckiens, Building Scalable Database Applications: Object-Oriented
          Design, Architectures, and Implementations Hofmeister/Nord/Dilip, Applied Software Architecture
          Jacobson/Booch/Rumbaugh, The Unified Software Development Process
          Jacobson/Ng, Aspect-Oriented Software Development with Use Cases
          Jordan, C++ Object Databases: Programming with the ODMG Standard
          Kleppe/Warmer/Bast, MDA Explained: The Model Driven ArchitectureTM: Practice and Promise
          Kroll/Kruchten, The Rational Unified Process Made Easy: A Practitioner’s Guide to the RUP</p>

          <p>
          Royce, Software Project Management: A Unified Framework
          Rumbaugh/Jacobson/Booch, The Unified Modeling Language Reference
          Manual Schneider/Winters, Applying Use Cases, 2E: A Practical Guide
          Smith, IBM Smalltalk Smith/Williams, Performance Solutions: A
          Practical Guide to Creating Responsive, Scalable Software
          Tkach/Fang/So, Visual Modeling Technique Tkach/Puttick, Object
          Technology in Application Development, Second Edition Unhelkar,
          Process Quality Assurance for UML-Based Projects Warmer/Kleppe,
          The Object Constraint Language, 2E: Getting Your Models Ready for MDA
          </p>

        </div>


        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Header</h2>
            <p>test</p>
          </a>
          <a className={styles.card}>
          Test
          </a>
          <a className={styles.card}>
            <h2>Header</h2>
            <p>test</p>
          </a>
        </div>


        <div className={styles.table}>
          <tr>
            <th>Link1</th>
            <th>Link2</th>
            <th>Link3</th>
          </tr>
          <tr>
            <td>Content1</td>
            <td>Content2</td>
            <td>Content3</td>
          </tr>
        </div>




      </main>
      <div className={styles.footer}>

      </div>
    </div>
  )
}
